### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by mickeyl** [fabianfett/pure-swift-json#69]
Thanks for this great project!

In the README, you state "It offers a significant performance improvement compared to the Foundation implementation on Linux.". While that's great as is, I wonder whether it could be beneficial to use this library also on Apple platforms.

Did you – by any chance – compare performance with their builtin JSON coding yet?

**Comment by slashmo** [comment]
Thanks for raising this issue. Did you already check out the ["Performance"](https://github.com/swift-extras/swift-extras-json#performance) section of the Readme? It includes comparisons for both Linux & macOS.

**Comment by slashmo** [comment]
Closing this for now. @mickeyl Please feel free to re-open if the ["Performance"](https://github.com/swift-extras/swift-extras-json#performance) section doesn't provide enough insights.
